Repository Khanhtran47/Sora, pull requests merged in 2023-03, with the labels that each got.

#344 fix: update sidebar and translations
  app/components/layouts/SideBar.tsx
  app/routes/genres/anime.tsx
  app/routes/genres/movie.tsx
  app/routes/genres/tv.tsx
  public/locales/en/discover.json
  public/locales/en/sidebar.json
  public/locales/fr/sidebar.json
  public/locales/vi/sidebar.json
Labels: bugfix, size/M

#345 fix: update scroll into view when changing pages
  app/components/media/AnimeDetail.tsx
  app/components/media/MediaDetail.tsx
  app/routes/collections/$collectionsId.tsx
  app/routes/movies/$movieId/cast.tsx
  app/routes/movies/$movieId/crew.tsx
  app/routes/movies/$movieId/recommendations.tsx
  app/routes/movies/$movieId/similar.tsx
  app/routes/tv-shows/$tvId.season.$seasonId/cast.tsx
  app/routes/tv-shows/$tvId.season.$seasonId/crew.tsx
  app/routes/tv-shows/$tvId/cast.tsx
  app/routes/tv-shows/$tvId/crew.tsx
  app/routes/tv-shows/$tvId/recommendations.tsx
  app/routes/tv-shows/$tvId/similar.tsx
Labels: size/M

#346 feat: add scrollable for sidebar
  app/components/elements/NavigationMenu.tsx
  app/components/layouts/Layout.tsx
  app/components/layouts/SideBar.tsx
  package.json
  tailwind.config.js
  yarn.lock
Labels: size/XXL

#349 feat: replace api by consumet lib
  app/components/elements/modal/SelectProviderModal.tsx
  app/components/elements/shared/WatchDetail.tsx
  app/components/layouts/GlobalPlayer.tsx
  app/root.tsx
  app/routes/anime/$animeId/episodes.tsx
  app/routes/anime/recent-episodes.tsx
  app/routes/api/provider.ts
  app/routes/movies/$movieId.tsx
  app/routes/movies/$movieId.watch.tsx
  app/routes/tv-shows/$tvId.season.$seasonId.episode.$episodeId.watch.tsx
  app/routes/tv-shows/$tvId.season.$seasonId.tsx
  app/routes/tv-shows/$tvId.season.$seasonId/index.tsx
  app/routes/tv-shows/$tvId.tsx
  app/services/consumet/anilist/anilist.server.ts
  app/services/consumet/anilist/anilist.types.ts
  app/services/consumet/anilist/utils.server.ts
  app/services/consumet/flixhq/flixhq.server.ts
  app/services/consumet/flixhq/flixhq.types.ts
  app/services/consumet/flixhq/utils.server.ts
  app/services/provider.server.ts
  app/services/tmdb/tmdb.server.ts
  package.json
  public/images/screenshot.png
  public/images/screenshot_2.png
  yarn.lock
Labels: size/XXL
